name: Deploy Flask App to ECS (OIDC Role-Based)

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-2
  APP_NAME: microservices-api
  ENV: dev
  DEPLOY_ROLE: Microservices-api-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get AWS Account ID
        id: aws-account
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "account_id=$ACCOUNT_ID" >> $GITHUB_OUTPUT

      - name: Set dynamic environment variables
        id: vars
        run: |
          ECR="${{ steps.aws-account.outputs.account_id }}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP_NAME}-${ENV}"
          ROLE="arn:aws:iam::${{ steps.aws-account.outputs.account_id }}:role/${DEPLOY_ROLE}"

          echo "ECR_REPO=$ECR" >> $GITHUB_ENV
          echo "ROLE_ARN=$ROLE" >> $GITHUB_ENV

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ECR_REPO

      - name: Build, Tag, and Push Docker Image
        run: |
          docker build -t ${APP_NAME}-${ENV} ./flask_app
          docker tag ${APP_NAME}-${ENV}:latest $ECR_REPO:latest
          docker push $ECR_REPO:latest
